package com.vardan.todo.mapper;

import com.vardan.todo.dto.request.TodoCreateRequest;
import com.vardan.todo.dto.response.TodoResponse;
import com.vardan.todo.entity.Category;
import com.vardan.todo.entity.Todo;
import com.vardan.todo.entity.User;
import com.vardan.todo.enums.Priority;
import com.vardan.todo.enums.TodoStatus;
import org.springframework.stereotype.Component;

/**
 * TodoMapper — The Translator between DTOs and Entities.
 *
 * WHAT IS A MAPPER?
 * -----------------
 * Your application has two "worlds":
 *   1. The OUTSIDE world (HTTP requests/responses) → uses DTOs
 *   2. The INSIDE world (database/business logic) → uses Entities
 *
 * The mapper translates between these two worlds.
 *
 * FLOW:
 *   Request comes in → Controller receives TodoCreateRequest (DTO)
 *                     → Mapper converts it to Todo (Entity)
 *                     → Service saves the Entity to database
 *                     → Mapper converts Entity back to TodoResponse (DTO)
 *                     → Controller sends TodoResponse back to user
 *
 * WHY @Component?
 * ---------------
 * This makes it a Spring Bean, so you can inject it into your Service using
 * constructor injection (just like you inject repositories).
 */
@Component
public class TodoMapper {

    /**
     * Converts a TodoCreateRequest (what the user sends) into a Todo entity (what the database stores).
     *
     * IMPORTANT: Notice what this method does NOT set:
     *   - id → auto-generated by JPA (@GeneratedValue)
     *   - createdAt / updatedAt → auto-set by @PrePersist / @PreUpdate in BaseEntity
     *   - deleted → defaults to false in the entity
     *   - user → must be set separately in the Service (from the logged-in user)
     *   - category → must be looked up by categoryId in the Service
     *
     * The mapper is intentionally "dumb" — it just maps fields.
     * The Service handles all the business logic (looking up categories, setting the user, etc.)
     *
     * @param request  The DTO from the user's HTTP request
     * @param user     The currently logged-in user (from @AuthenticationPrincipal)
     * @param category The category entity (looked up by categoryId), can be null
     */
        public Todo toEntity(TodoCreateRequest request, User user, Category category) {
        return Todo.builder()
                .title(request.getTitle())
                .description(request.getDescription())
                .priority(request.getPriority() != null ? request.getPriority() : Priority.MEDIUM)
                // If user didn't specify a priority, default to MEDIUM
                .status(TodoStatus.PENDING) // New todos always start as PENDING
                .dueDate(request.getDueDate())
                .deleted(false)
                .user(user)       // Attach this todo to the logged-in user
                .category(category) // Can be null if no category was specified
                .build();
    }

    /**
     * Converts a Todo entity (from the database) into a TodoResponse (what the user sees).
     *
     * Notice how we "flatten" the Category:
     *   - Instead of: "category": { "id": "...", "name": "Work", "color": "#FF0000", "user": { ... } }
     *   - We return:  "categoryId": "...", "categoryName": "Work"
     *
     * This prevents:
     *   1. Circular references (Category → User → Todos → Category → ...)
     *   2. Exposing unnecessary data (the user already knows their own info)
     *   3. Large response sizes
     */
    public TodoResponse toResponse(Todo todo) {
        return TodoResponse.builder()
                .id(todo.getId())
                .title(todo.getTitle())
                .description(todo.getDescription())
                .status(todo.getStatus())
                .priority(todo.getPriority())
                .dueDate(todo.getDueDate())
                .createdAt(todo.getCreatedAt())
                .updatedAt(todo.getUpdatedAt())
                // Safely extract category info (might be null if no category was assigned)
                .categoryId(todo.getCategory() != null ? todo.getCategory().getId() : null)
                .categoryName(todo.getCategory() != null ? todo.getCategory().getName() : null)
                .build();
    }
}